services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - my-bank

networks:
  my-bank:
    driver: bridge