name: Deploy to EC2

on:
  push:
    branches:
      - main  # или твоя основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug SSH key (временно!)
        run: |
          ls -la ~/.ssh
          head -n 5 ~/.ssh/id_rsa || echo "No key found"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            # Стоп и удаление старого контейнера (если есть)
            docker stop gateway || true
            docker rm gateway || true

            # Удаление старого образа
            docker rmi gateway:latest || true

            # Клонирование проекта заново
            rm -rf gateway || true
            git clone https://github.com/artem-nikeienko/my-bank-gateway.git
            cd gateway

            # Сборка и запуск
            docker build -t gateway .
            docker run -d --name gateway -p 3000:3000 gateway
          EOF
